- name: Ensure subnets exist within VPC.
  ec2_vpc_subnet:
    vpc_id: "{{ec2_vpc_id}}"
    cidr: "{{item.value.cidr}}"
    resource_tags:
      Name: "{{item.key}}"
  with_dict: "{{ec2_subnets}}"

- name: Store VPC subnet facts for future use
  ec2_vpc_subnet_facts:
    filters:
      vpc-id: "{{ec2_vpc_id}}"
    region: "{{ec2_region}}"
  register: ec2_subnet_details
  tags: always
