---
- name: Create temp workspace for Docker build.
  tempfile:
    state: directory
  register: temp_docker_db_ws

- name: Template out the files to Docker workspace.
  template:
    src: '{{item}}'
    dest: '{{temp_docker_db_ws.path}}'
  with_items:
  - mwdatabase.sql
  - Dockerfile

- name: Include task to execute ECR Login.
  include_role:
    name: common
    tasks_from: ecr-login

- name: Build a MySQL DB Docker Image with MediaWiki DB initialization and push to ECR.
  docker_image:
    name: '{{ecr_repo_url_db}}'
    tag: '{{mw_db_ver}}'
    path: '{{temp_docker_db_ws.path}}'
    push: yes

- name: Create a DB Docker container which initializes the MediaWiki DB.
  docker_container:
    name: '{{mw_db_name}}'
    image: '{{ecr_repo_url_db}}:{{mw_db_ver}}'
    state: started
    ports:
     - "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: '{{vault_mysql_root_pass}}'
      MYSQL_USER: '{{mysql_db_user}}'
      MYSQL_PASSWORD: '{{vault_mysql_pass}}'
      MYSQL_DATABASE: '{{mysql_db_name}}'
