# Canonical Ubuntu 16.04 Server. Details retrieved from AWS Console.
ec2_ubuntu_owner: 099720109477
ec2_ubuntu_ami_name: 'ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180814'

# Create VMs with Public IP.
public_ip: true

user_data: |
  #!/bin/bash
  apt-get update -qqy
  apt-get install -y python python-pip
