---
# ensure prereqs on localhost
- block:
  - name: ensure pip is installed on localhost
    apt:
      name: python-pip
      state: present
  - name: ensure pip packages are installed on localhost
    pip:
      name: "{{item}}"
      state: present
    with_items:
    - boto3

# Note: we need AWS CLI 1.16+. Older versions do not have the --no-include-email flag.

  - name: Install AWS CLI latest version using Pip. (Some AWS modules like ECR require AWS CLI).
    pip:
      name: 'awscli'
      state: present

  - name: include a role to generate ECR login token.
    include_role:
      name: common
      tasks_from: generate-ecr-login
  delegate_to: localhost
  become: true
