- hosts: localhost
  connection: local
  vars:
    use_azure: true
    use_sshkey_auth: true
    ssh_key_path: ~/.ssh/id_rsa
    rg_name: jenkins
    vm_name: jenkins
    location: eastus
    vm_groups:
    - jenkins
  roles:
  - ansible-roles/azurevm
  - ansible-roles/updateinventory
  tasks:
  - debug: var=vault_vm_password
    tags: password
- hosts: jenkins
  roles:
    - { role: geerlingguy.java, become: true }
    - { role: ansible-roles/install-docker, become: true }
    - { role: ansible-roles/jenkins, become: true }
    - { role: registry, become: true }
