---
# tasks file for roles/prometheus-grafana

- name: Create a temporary Docker workspace
  tempfile:
    state: directory
  register: tempdir

- name: Change permissions.
  file:
    name: '{{tempdir.path}}'
    state: directory
    mode: 0777

- name: Template out Prometheus Dockerfile to {{tempdir.path}}
  template:
    src: Dockerfile_prometheus
    dest: '{{tempdir.path}}'
    mode: 0777

- name: Template out Prometheus Config to {{tempdir.path}}
  template:
    src: prometheus.yml
    dest: '{{tempdir.path}}'
    mode: 0777

- block:
  - name: Build Prometheus Docker Image.
    docker_image:
      path: '{{tempdir.path}}'
      dockerfile: Dockerfile_prometheus
      name: prometheus_img

  - name: Create a network
    docker_network:
      name: '{{mon_docker_network_name}}'

  - name: Create Prometheus Container
    docker_container:
      name: prometheus_container
      image: prometheus_img
      state: started
      ports:
       - "{{prom_port}}:{{prom_port}}"
      networks:
      - name: '{{mon_docker_network_name}}'

  - name: Create Grafana Container
    docker_container:
      name: grafana_container
      image: 'grafana/grafana:{{grafana_version}}'
      state: started
      ports:
       - "{{grafana_port}}:{{grafana_port}}"
      networks:
      - name: '{{mon_docker_network_name}}'
  become: yes
  become_user: docker

- uri:
    url: '{{grafana_api_root}}/datasources'
    method: GET
    user: admin
    password: admin
    force_basic_auth: yes
  register: grafana_datasources

- set_fact: create_datasource={{ grafana_datasources.json|length == 0 }}

- uri:
    url: '{{grafana_api_root}}/datasources'
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    body: |
      {
      "name":"prometheus",
      "type":"prometheus",
      "access":"proxy",
      "url":"http://prometheus_container:{{prom_port}}",
      "basicAuth": true,
      "basicAuthUser":"admin",
      "basicAuthPassword":"admin",
      "isDefault": true
      }
    body_format: json
  when: create_datasource
