---
- name: Check if Login Secret exists in kube.
  shell: kubectl get secret {{kube_secret}}
  ignore_errors: yes
  register: kube_existing_secret

- name: Delete Login Secret if it exists. This is because its a temporary secret valid for 12 hours.
  shell: kubectl delete secret {{kube_secret}}
  when: kube_existing_secret is not failed

- name: Generate Login Secret.
  shell: |
    kubectl create secret docker-registry {{kube_secret}} --docker-server={{ecr_repo_root}} \
    --docker-username={{ hostvars['localhost']['aws_ecr_login_username'] }} \
    --docker-password={{ hostvars['localhost']['aws_ecr_login_token'] }}
