---
- name: Get existing Kubernetes deployments.
  shell: kubectl get deployments
  changed_when: false
  register: kube_deployments

- include_tasks: deploy.yml
  when: kube_deployment not in kube_deployments.stdout
