---
- name: Get existing Kubernetes deployments.
  shell: kubectl get deployments
  changed_when: false
  register: kube_deployments

- block:
  - include_tasks: createloginsecret.yml
  - include_tasks: createdbservice.yml
  - include_tasks: deploy.yml
  when: kube_deployment not in kube_deployments.stdout

- name: Retrieve load-balancer address. Wait until it is available.
  shell: kubectl get service {{kube_deployment}} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
  register: kube_lb_addr
  until: kube_lb_addr.stdout | length > 0
  timeout: 120
  delay: 10
  sleep: 10
