---
- name: Ensure prerequisites on localhost.
  hosts: localhost
  connection: local
  vars_files:
  - common_vars.yml
  roles:
  - prereqs

- name: Ensure prerequisites on EC2 instances.
  hosts: all
  vars_files:
  - common_vars.yml
  roles:
  - {role: ansible-roles/install-docker, tags: docker}

- name: Create a DB Docker Image, Push to ECR and run a container initialized with MediaWiki Schema.
  hosts: tag_Name_mysql
  vars_files:
  - common_vars.yml
  roles:
  - db

- name: Create Docker container for MediaWiki.
  hosts: tag_Name_mw
  vars_files:
  - common_vars.yml
  roles:
  - mw-image
