---
# localhost prerequisites are required by all future plays.
# we append the "always" tag to ensure the play runs
# even if we are running with --tag=<something>.

# at time of writing, Chef is installed on my Windows machine.
# Ansible run through WSL tries to use Ohai to locate localhost facts, which I don't want.
# So I disabled gather_facts for localhost.

- name: Ensure prerequisites and install Docker on localhost.
  hosts: localhost
  connection: local
  vars_files:
  - common_vars.yml
  roles:
  - prereqs
  - ansible-roles/install-docker
  tags: always

- name: Ensure prerequisites on DB EC2 Instance.
  hosts: tag_Name_mysql
  vars_files:
  - common_vars.yml
  roles:
  - ansible-roles/install-docker

- name: Create DB and MW Docker Images, Push to ECR
  hosts: localhost
  connection: local
  vars_files:
  - common_vars.yml
  roles:
  - images
  tags: images

- name: Create DB Docker Container.
  hosts: tag_Name_mysql
  vars_files:
  - common_vars.yml
  roles:
  - db
