- name: Create AWS Elastic Container Registry repositories in ECS.
  hosts: localhost
  connection: local
  vars_files:
  - common_vars.yml
  tasks:
  - name: create ECR repo.
    ecs_ecr:
      name: '{{item}}'
      state: present
    with_items:
    - '{{ecr_repo_name_app}}'
    - '{{ecr_repo_name_db}}'
