---
- name: Generate ECR Login.
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - common_vars.yml
  tasks:
  - name: include a role to generate ECR login token on localhost.
    include_role:
      name: common
      tasks_from: generate-ecr-login

- name: Deploy the app on Kubernetes cluster.
  hosts: tag_Name_mw
  vars_files:
  - common_vars.yml
  roles:
  - kubeservice
  tags: deploy
