---

# Ref:
# https://docs.ansible.com/ansible/2.5/user_guide/playbooks_filters.html
# https://stackoverflow.com/questions/37160668/check-if-strings-are-equals-and-ternary-operator-in-ansible
# https://stackoverflow.com/questions/30987865/can-roles-and-tasks-exist-in-the-same-playbook

# We use pre_tasks to Specify facts for kubernetes master
# because the vars need to be set before kubernetes role runs.
# We exploit the fact that ec2_ami_launch_index is set to 0 for the first node.

- name: Install Kubernetes and make the first MediaWiki node the master.
  hosts: tag_Name_mw
  vars_files:
  - common_vars.yml
  pre_tasks:
  - name: Make the first MW node the Kubernetes master.
    set_fact:
      kubernetes_role: '{{"master" if inventory_hostname == groups["tag_Name_mw"][0] else "node" }}'
      kubernetes_apiserver_advertise_address: '0.0.0.0'
  - debug: var=kubernetes_role
  roles:
  - {role: geerlingguy.kubernetes, become: true}
  tags: kubemaster

# - name: Install Kubernetes and make the first MediaWiki node the master.
#   hosts: tag_Name_mw[0]
#   vars_files:
#   - common_vars.yml
#   pre_tasks:
#   - name: Make the first MW node the Kubernetes master.
#     set_fact:
#       kubernetes_role: "master"
#       kubernetes_apiserver_advertise_address: '0.0.0.0'
#   roles:
#   - {role: geerlingguy.kubernetes, become: true}
#   tags: kubemaster
#
# - name: Install Kubernetes and make the other MediaWiki nodes the nodes.
#   hosts: tag_Name_mw[1:]
#   vars_files:
#   - common_vars.yml
#   pre_tasks:
#   - name: Make the other MW node the Kubernetes node. Get join command from master.
#     set_fact:
#       kubernetes_role: "node"
#       kubernetes_join_command: "{{hostvars[ groups['tag_Name_mw'][0] ]['kubernetes_join_command'] }}"
#   roles:
#   - {role: geerlingguy.kubernetes, become: true}
#   tags: kubenode
