---
- name: Install Kubernetes.
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - common_vars.yml

  tasks:
  - name: Create an EKS cluster
    aws_eks_clusterddddd: my_cluster
      role_arn: my_eks_role
      subnets:
      - subnet-aaaa1111
      security_groups:
      - my_eks_sg
      - sg-abcd1234
      register: caller_facts
 
