- name: create Azure VMs.
  hosts: localhost
  connection: local
  vars_files:
  - vars_linux.yml
  roles:
  - { role: ansible-roles/azure-vnet }
  - { role: ansible-roles/azurevm }
  - { role: ansible-roles/updateinventory, tags: always }

  tasks:
  - debug: var=vault_vm_password
    tags: password

- name: provision prometheus and grafana.
  hosts: monitoring
  roles:
  - { role: ansible-roles/install-docker }
  - prometheus-grafana
  tags: prom
